name: Docker Image CI

on: [push, pull_request]

jobs:

  build:
    name: build ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - 7.1
          - 7.2
          - 7.3
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Build the Docker image version
      run: docker build -t ${{ github.repository }}:${{ matrix.version }} ./${{ matrix.version }}
